### ISSUE TITLE
[enhancement]: Silence experimental warnings in console

### ISSUE THREAD

**Issue by lukahartwig** [remix-run/remix#1141]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

16.13.1

### Steps to Reproduce

1. Create a new remix project with `npx create-remix@latest`
2. Start the dev server

```
$ NODE_OPTIONS=--trace-warnings npm run dev

> dev
> remix dev

(node:3485) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at node:stream/web:7:1
    at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
    at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
    at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
    at Function.Module._load (node:internal/modules/cjs/loader:804:15)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/luka/SideProjects/my-remix-app/node_modules/@web-std/stream/src/stream.cjs:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
(node:3485) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at new Blob (node:internal/blob:142:5)
    at use (/home/luka/SideProjects/my-remix-app/node_modules/@web-std/blob/dist/src/blob.node.cjs:39:24)
    at Object.<anonymous> (/home/luka/SideProjects/my-remix-app/node_modules/@web-std/blob/dist/src/blob.node.cjs:46:14)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
Watching Remix app in development mode...
💿 Built in 268ms
Remix App Server started at http://localhost:3000
```

### Expected Behavior

Warnings should not appear. This is a regression as downgrading to `1.0.6` makes the warnings disappear.

### Actual Behavior

The warnings are logged.

**Comment by lukahartwig** [comment]
Although this doesn't break anything these warnings also show up in the logs on Vercel which triggers my alerting because they are marked as errors.
```
:03.675Z	undefined	ERROR	(node:9) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
```
Currently this prevents me from upgrading to `1.1.x`.

**Comment by luffy84217** [comment]
@lukahartwig Are you fixing it right now?

**Comment by lukahartwig** [comment]
I opened an issue in the repo of the sub dependency that is causing this.

The other option I see would be to replace `@web-std/file` but this should be coordinated with the Remix maintainers first.

**Comment by AhmedBHameed** [comment]
Yup, I confirm this error

```bash
(node:2689510) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
```

**Comment by binajmen** [comment]
Same here
```
> NODE_OPTIONS=--trace-warnings yarn dev

yarn run v1.22.17
$ remix dev
(node:67612) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at node:stream/web:7:1
    at NativeModule.compileForInternalLoader (node:internal/bootstrap/loaders:312:7)
    at NativeModule.compileForPublicLoader (node:internal/bootstrap/loaders:252:10)
    at loadNativeModule (node:internal/modules/cjs/helpers:49:9)
    at Function.Module._load (node:internal/modules/cjs/loader:804:15)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/benjamin/Projects/fbnb-exam-remix/node_modules/@web-std/stream/src/stream.cjs:2:20)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
(node:67612) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
    at emitExperimentalWarning (node:internal/util:224:11)
    at new Blob (node:internal/blob:142:5)
    at use (/Users/benjamin/Projects/fbnb-exam-remix/node_modules/@web-std/blob/dist/src/blob.node.cjs:39:24)
    at Object.<anonymous> (/Users/benjamin/Projects/fbnb-exam-remix/node_modules/@web-std/blob/dist/src/blob.node.cjs:46:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
Watching Remix app in development mode...
💿 Built in 299ms
Remix App Server started at http://192.168.1.41:3000
```

**Comment by huyng12** [comment]
Any update guys? I am facing the warnings too.

**Comment by johncarmack1984** [comment]
Got this one all up in my console as well

**Comment by alexisbellido** [comment]
Any updates on fixing this?

**Comment by andresgutgon** [comment]
I know is not the solution but this (`NODE_OPTIONS=--no-warnings`) remove the warnings:

```
NODE_OPTIONS=--no-warnings node -r dotenv/config node_modules/.bin/remix dev
```

**Comment by chaance** [comment]
We understand these warnings are noisy, but it's not a bug nor is it a problem for your app. We do use these features and you will get the flag as a result. It's on our radar so no need to ping the issue. We'll update when we've made any changes here.

**Comment by machour** [comment]
This appears to have been fixed since then.

**Comment by danharten-sovtech** [comment]
I still get the warning today while working through the quick-start:

```
{
  "name": "my-remix-app",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "remix dev -c \"node server.mjs\""
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@remix-run/express": "^2.2.0",
    "@remix-run/node": "^2.2.0",
    "@remix-run/react": "^2.2.0",
    "express": "^4.18.2",
    "isbot": "^3.7.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@remix-run/dev": "^2.2.0"
  }
}
```
