### ISSUE TITLE
[Bug]: Redirecting from an action called using useFetcher does not reload loaders

### ISSUE THREAD

**Issue by Aravindh-SNR** [remix-run/remix#1616]
### What version of Remix are you using?

1.1.1

### What version of Node are you using? Minimum supported version is 14.

14.8.0

### Steps to Reproduce

1. From route X, make a HTTP request to a resource route using useFetcher Form.
2. From the action of the resource route, redirect to route Y.

### Expected Behavior

Loaders of route Y should be reloaded.

### Actual Behavior

Loaders of route Y are not reloaded.

https://user-images.githubusercontent.com/22143573/150655379-244484e0-5605-41b6-9284-e6864f4dd8b5.mp4

In the video:
1. I'm on the route /admin/edit/$slug
2. I delete the post 'Post 3' which calls the resource route /admin/delete/$slug
3. The resource route deletes the post and redirects to the route /admin/edit
4. 'Post 3' is still visible in the route /admin/edit because the loaders are not reloaded

(If this is not a bug and I've misunderstood something, please let me know and sorry for the trouble)

**Comment by jacob-ebey** [comment]
How are you submitting the form? Can you show both that code and your form JSX? Loaders are not re-called unless the form submit is a POST request, GET form submissions do not invalidate parent loaders.

**Comment by Aravindh-SNR** [comment]
@jacob-ebey I'm doing a DELETE request.

Here is the form JSX:
```
import { useFetcher, useParams } from 'remix';

const DeletePostForm = () => {
    const deletePost = useFetcher();
    const params = useParams();

    return (
        <deletePost.Form
            method='delete'
            action={`/admin/delete/${params.slug}`}
        >
            <button
                type='submit'
            >
                {
                    deletePost.submission
                        ? 'Deleting...'
                        : 'Delete'
                }
            </button>
        </deletePost.Form>
    );
};

export default DeletePostForm;
```
Here is the action for the resource route (/admin/delete/$slug):
```
export const action = async ({ params }) => {
    const { slug } = params;

    await new Promise(resolve => setTimeout(resolve, 1000));

    await fs.unlink(
        path.join(postsPath, `${slug}.md`)
    );

    return redirect('/admin/edit');
};
```

**Comment by viczam** [comment]
I was able to replicate the issue: it happens with any POST, DELETE etc. request.

**Comment by charklewis** [comment]
I am able to replicate issue also. I have mentioned this in the discussions - https://github.com/remix-run/remix/discussions/1944

**Comment by nicksrandall** [comment]
I'm also facing this issue.

**Comment by ryanflorence** [comment]
Mostly fixed in #1875 (v1.2.3) completely fixed in 193cdecef61930c886b472405891e982284068ad (will be released next Tuesday).

**Comment by nicksrandall** [comment]
I'm still seeing this issue in the latest (1.3.1) release. @charklewis @viczam @Aravindh-SNR can you confirm if this has actually been fixed for you?

@ryanflorence  I'd offer to submit a PR with a failing test case but I'm not sure how to test that the loaders get recalled. I'd have to look into that more.

**Comment by charklewis** [comment]
@nicksrandall I just did some testing and the bug is still there. I am solving it at the moment by returning a blank `200` from the action and redirecting on the client (in the browser), which intuitively isn't ideal.

**Comment by nicksrandall** [comment]
@ryanflorence if you could re-open this issue, that would be great. Thank you!

**Comment by franzwarning** [comment]
Seeing this as well

**Comment by fergusmeiklejohn** [comment]
I've seen this sort of behaviour too: useFetcher() doesn't always call the loaders when I redirect

**Comment by brophdawg11** [comment]
Looks like we missed one conditional for the revalidation, this should be fixed by https://github.com/remix-run/remix/pull/2838

**Comment by daniel-a-marshall** [comment]
I'm still seeing this issue using useFetcher. The redirect from the loader is not called.

**Comment by machour** [comment]
@daniel-a-marshall Please open a new issue with all the details for repro.

**Comment by nicksrandall** [comment]
@machour @daniel-a-marshall My PR mentioned above has a failing test that can reproduce the issue.

**Comment by machour** [comment]
@nicksrandall I reopened it to run tests again, but it has conflicts. If you're still see this issue, which was supposedly fixed in April, would you mind reopening a new PR with a failing test ?

**Comment by charklewis** [comment]
I have done some testing on the latest version `1.7.5` and this looks like it is still a bug 😥 Has there been any progress on this issue?

**Comment by machour** [comment]
@charklewis  Please open a new issue with all the details for repro

**Comment by charklewis** [comment]
> @charklewis Please open a new issue with all the details for repro

No worries! I'll make a new issue including how to reproduce over the weekend.

**Comment by segheysens** [comment]
@charklewis Did you come to a conclusion this? I think that I'm encountering something similar.
