### ISSUE TITLE
[Bug]: Live reload not working with Architect server

### ISSUE THREAD

**Issue by denodell** [remix-run/remix#1756]
### Which Remix packages are impacted?

- [ ] `remix` (Remix core)
- [ ] `create-remix`
- [X] `@remix-run/architect`
- [ ] `@remix-run/cloudflare-workers`
- [ ] `@remix-run/dev`
- [ ] `@remix-run/express`
- [ ] `@remix-run/netlify`
- [ ] `@remix-run/node`
- [ ] `@remix-run/react`
- [ ] `@remix-run/serve`
- [ ] `@remix-run/server-runtime`
- [ ] `@remix-run/vercel`

### What version of Remix are you using?

1.1.3

### What version of Node are you using? Minimum supported version is 14.

16

### Steps to Reproduce

Run `npx create-remix@latest` and create a new project.
Run `arc sandbox` and `nom run dev` in two separate processes.
Browse to site, in my case http://localhost:3333

### Expected Behavior

Live reload functionality should work, the browser should update when changing code in a route.

### Actual Behavior

Live reload does not update the browser, and there is an error shown in the dev tools console:

```
Warning: Expected server HTML to contain a matching <script> in <body>.
script
LiveReload@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:3284:7
body
html
App
RemixRoute@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:3021:5
Routes@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:3009:27
Router2@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:484:18
RemixCatchBoundary@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:1564:18
RemixErrorBoundary@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:1489:10
RemixEntry@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:2906:24
RemixBrowser@http://localhost:3333/_static/build/_shared/chunk-LAE5MDMM.js:3313:33
```

**Comment by confix** [comment]
As a temporary workaround, you can copy the LiveReload code from https://github.com/remix-run/remix/blob/f361f11c87abf37368528fdafc563bb8c9dbb201/packages/remix-react/components.tsx#L1276 into your project and use that instead. At least that did the trick for me.

I don't know too much about remix internals (yet). Probably someone could point me into the right direction? I would love helping to fix the issue!

**Comment by confix** [comment]
Can you try setting `NODE_ENV` to `development` in your start script for architect?

```
{
   ...
   "scripts": {
     ...
     "start": "NODE_ENV=development arc sandbox" 
   }
}
```

It seems like the architect sandbox sets `NODE_ENV` to `testing` for the server, hence `LiveReload` does not render the script on the server.

Might be cool to add that to the docs once you can confirm it works for you too.

**Comment by denodell** [comment]
Hey @confix , thanks for the tip! Whilst adding `NODE_ENV=development` to the script call itself didn't work, what DID work was adding that line to my `preferences.arc` file, which now looks like this:

```
# The @env pragma is synced (and overwritten) by running arc env
@env
testing
  NODE_ENV development
  REMIX_ENV development

staging
  REMIX_ENV production

production
  REMIX_ENV production
```

I'll see if I can raise a PR for this.

**Comment by jacob-ebey** [comment]
Thanks for the submission. This has already been merged on the dev branch: https://github.com/remix-run/remix/pull/1749/files#diff-6c273df8f051fa5f013769c5e8c2545d0df0145f9abccf1b02763ec97fc3ff00

**Comment by confix** [comment]
Probably running on Windows (I am a Linux user)? Crossenv should work then. Your suggestion did not work for me, tho... after all the issue seems to be the env variable not being set correctly.

**Comment by denodell** [comment]
> Probably running on Windows (I am a Linux user)? Crossenv should work then. Your suggestion did not work for me, tho... after all the issue seems to be the env variable not being set correctly.

Mac, actually! At least the bug is fixed in the next release!

**Comment by gpmcadam** [comment]
Despite being merged, `preferences.arc` was later added to `.gitignore` and as far as I can tell this issue is still present. Is there some better way to resolve this?

**Comment by tnightingale** [comment]
FWIW this seems to be caused by a mismatch between [Architect's automatic .env file support](https://arc.codes/docs/en/reference/configuration/local-preferences#.env-file-support) and Remix's [`<LiveReload>` component's dead code elimination](https://github.com/remix-run/remix/blob/main/packages/remix-react/components.tsx#L1378-L1381).

Adding a `.env` file containing `NODE_ENV=development` seems to address the issue in a local development environment. Eg:
```env
# .env
NODE_ENV=development
# ...other application environment variables
```

**Comment by machour** [comment]
@tnightingale would be awesome to have a PR to mention this in the README if you're up for it

**Comment by machour** [comment]
@denodell does the last release fix the bug for you?
