### ISSUE TITLE
remix-run + cloudflare-pages breaks using React 18

### ISSUE THREAD

**Issue by timfee** [remix-run/remix#2625]
### What version of Remix are you using?

1.3.4

### Steps to Reproduce

1. Create a new project, `yarn create remix`
2. Use TypeScript and choose **Cloudflare Pages** when prompted.
3. Run `yarn dev`
4. Observe everything works
5. Update `react` and `react-dom` to `18.0` in `package.json`
6. Run `yarn` and then `yarn dev`
7. Observe the error (in "Actual Behavior")

(also cross-posted to `wrangler2` at https://github.com/cloudflare/wrangler2/issues/754)

### Expected Behavior

Development server runs

### Actual Behavior

Error: 

```
yarn run v1.22.18
$ remix build && run-p dev:*
Building Remix app in production mode...
Built in 120ms
$ remix watch
$ cross-env NODE_ENV=development wrangler pages dev ./public
Watching Remix app in development mode...
🚧 'wrangler pages <command>' is a beta command. Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Compiling worker to "/var/folders/63/p41w7l2j5rdgvdf8p4f21zz00000gn/T/functionsWorker.js"...
💿 Built in 169ms
Compiled Worker successfully.
[pages:err] ReferenceError: Buffer is not defined
    at E (/Users/timfee/Sites/foobar/functions/[[path]].js:21:17168)
    at /Users/timfee/Sites/foobar/functions/[[path]].js:21:22309
    at /Users/timfee/Sites/foobar/functions/[[path]].js:1:808
    at /Users/timfee/Sites/foobar/functions/[[path]].js:29:16246
    at /Users/timfee/Sites/foobar/functions/[[path]].js:1:808
    at /Users/timfee/Sites/foobar/functions/[[path]].js:44:7072
    at SourceTextModule.evaluate (node:internal/vm/module:224:23)
    at VMScriptRunner.runAsModule (/Users/timfee/Sites/foobar/node_modules/@miniflare/runner-vm/src/index.ts:38:18)
    at VMScriptRunner.run (/Users/timfee/Sites/foobar/node_modules/@miniflare/runner-vm/src/index.ts:82:17)
    at EventTarget.#reload (/Users/timfee/Sites/foobar/node_modules/@miniflare/core/src/index.ts:737:13)
Could not start Miniflare.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by styxlab** [comment]
The same error surfaces also with the cloudflare worker template.

**Comment by omarkhatibco** [comment]
@styxlab @timfee it's fixed in here #1977 and should be included with v1.3.5

**Comment by timfee** [comment]
confirmed this fixes the repro case -- thank you! :)

**Comment by styxlab** [comment]
Still seeing this issue with cloudflare-workers. Will ioen a new issue.
