### ISSUE TITLE
Add support for charSet meta tag

### ISSUE THREAD

**Issue by jensmeindertsma** [remix-run/remix#281]
Currently the only way to include a `<meta charSet="utf-8" />` is by adding it to the JSX in `root.jsx`. You can add `charSet: "utf-8"` to the `meta` function but it will be transformed into `<meta name="charSet" content="utf-8" />` which doesn't provide any value. Since there is already an exception for `title` with the `meta` function, I think Remix should also add an exception to transform `charSet: "utf-8"` into `<meta charSet="utf-8" />`.

I've included a patch file with the necessary changes.

#### Patch file contents
```
diff --git a/node_modules/@remix-run/react/browser/components.js b/node_modules/@remix-run/react/browser/components.js
index 8bd4568..27cddc0 100644
--- a/node_modules/@remix-run/react/browser/components.js
+++ b/node_modules/@remix-run/react/browser/components.js
@@ -434,7 +434,10 @@ function Meta() {
 
   return /*#__PURE__*/React.createElement(React.Fragment, null, Object.keys(meta).map(name => name === "title" ? /*#__PURE__*/React.createElement("title", {
     key: "title"
-  }, meta[name]) : name.startsWith("og:") ?
+  }, meta[name]) : name === "charSet" ? /*#__PURE__*/React.createElement("meta", {
+    key: name,
+    charSet: meta[name]
+  }) : name.startsWith("og:") ?
   /*#__PURE__*/
   // Open Graph protocol - https://ogp.me/
   React.createElement("meta", {
diff --git a/node_modules/@remix-run/react/components.js b/node_modules/@remix-run/react/components.js
index 97190b7..cd961c1 100644
--- a/node_modules/@remix-run/react/components.js
+++ b/node_modules/@remix-run/react/components.js
@@ -441,7 +441,10 @@ function Meta() {
 
   return /*#__PURE__*/React__default['default'].createElement(React__default['default'].Fragment, null, Object.keys(meta).map(name => name === "title" ? /*#__PURE__*/React__default['default'].createElement("title", {
     key: "title"
-  }, meta[name]) : name.startsWith("og:") ?
+  }, meta[name]) : name === "charSet" ? /*#__PURE__*/React__default['default'].createElement("meta", {
+    key: name,
+    charSet: meta[name]
+  }) : name.startsWith("og:") ?
   /*#__PURE__*/
   // Open Graph protocol - https://ogp.me/
   React__default['default'].createElement("meta", {
```

**Comment by machour** [comment]
I think that the `<meta charSet="utf-8" />` tag would be usually hardcoded in root.tsx, not generated via `<Meta />`, so not sure if this addition is useful.

**Comment by MichaelDeBoey** [comment]
Fixed by #2325

**Comment by machour** [comment]
@MichaelDeBoey nice work.
We're still missing http-equiv if you're up for it: https://github.com/remix-run/remix/issues/941
