### ISSUE TITLE
`Form` post submission does not retain search parameters

### ISSUE THREAD

**Issue by TheRealFlyingCoder** [remix-run/remix#3133]
### What version of Remix are you using?

1.4.3

### Steps to Reproduce

Impement a route that includes search params in the url.

`/my-route?param=1234`

On the page include a post form

```
<Form method="post">
        <button type="submit>Submit</button>
</Form>
```

Native browser behaviour can be seen here thanks to @kiliman

https://codesandbox.io/s/form-action-params-8r86qw?file=/app/routes/test.tsx:732-987

### Expected Behavior

Following the native browser behaviour, this should post back to `/my-route?param=1234`

Note that a `method="get"` post would natively replace the search params by the nature of the submission method

### Actual Behavior

The form will post to the base path `/my-route` and trim off the search params

**Comment by kiliman** [comment]
@manV Yes, fixing this issue will solve your scenario.

You can "fix" it now, by manually specifying your action.
```ts
const location = useLocation()
return <Form action={`${location.pathname}${location.search}`}/>
```
The actual fix is to essentially do this automatically if action is not specified, as that is standard browser behavior.

**Comment by nivekithan** [comment]
I think problem lies in `useFormAction`, 

https://github.com/remix-run/react-router/blob/931cf23a54373485607b3727dbd5f9575fe58ebe/packages/react-router/lib/hooks.tsx#L244-L256

As of now code looks like this 
```typescript
export function useFormAction(
  action = ".",
  // TODO: Remove method param in v2 as it's no longer needed and is a breaking change
  method: FormMethod = "get"
): string {
  let { id } = useRemixRouteContext();
  let path = useResolvedPath(action);
  let search = path.search;
  let isIndexRoute = id.endsWith("/index");

  if (action === "." && isIndexRoute) {
    search = search ? search.replace(/^\?/, "?index&") : "?index";
  }

  return path.pathname + search;
}
```

According to docs for `useResolvedPath` from  https://reactrouter.com/docs/en/v6/hooks/use-resolved-path

```
This hook resolves the pathname of the location in the given to value against the pathname of the current location.
```

I think what that means is that only resolves only `pathName` and  ignores the `search` key. Therefore returned value from `useResolvedPath` looks like this

```ts
{hash: ""
pathname: "/login"
search: ""}
```

even when the `url` is `/login?redirectTo=%2Fsettings`. I am not sure whether it is intended behaviour or not.

At commit  a3ae536f25bbb1d0cf93d06082b04741c8edae34 

the code was changed from

```ts
export function useFormAction(action = "."): string {
  let path = useResolvedPath(action);
  let location = useLocation();
  return path.pathname + location.search;
}
```

to this 
```ts
export function useFormAction(action = "."): string {
  let { id } = useRemixRouteContext();
  let path = useResolvedPath(action);
  let search = path.search;

  let isIndexRoute = id.endsWith("/index");

  if (isIndexRoute && action === ".") {
    search = "?index";
  }

  return path.pathname + search;
}
```


As you can see previously we have used only `useLocation` to get `search` not `useResolvedPath`, so I thought changing 
```ts
let search = path.search;
```

to this will work

```ts
let search = useLocation().search;
```

it did, but now I am getting whole new error
```
Warning: Prop `action` did not match. Server: "/login" Client: "/login?redirectTo=%2Fsettings"
    at form
    at http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4698:3
    at Form
    at label
    at div
    at LoginPage (http://localhost:3000/build/routes/login-QKI5NRX4.js:15:16)
    at RemixRoute (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4352:3)
    at Outlet (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:2559:26)
    at body
    at html
    at App
    at RemixRoute (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4352:3)
    at Routes2 (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4335:7)
    at Router (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:2563:15)
    at RemixCatchBoundary (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:2848:10)
    at RemixErrorBoundary (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:2773:5)
    at RemixEntry (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4232:12)
    at RemixBrowser (http://localhost:3000/build/_shared/chunk-D4PYBZR3.js:4921:27)
```

Now I have no idea on what this error is or where it is originating from and therefore I have no idea on how to solve it.

**Comment by ionut-botizan** [comment]
@nivekithan 
> Now I have no idea on what this error is or where it is originating from and therefore I have no idea on how to solve it.

Did you, by any chance, modified the transpiled Remix code in `node_modules` directly? 😁
If you did, then there are 2 places where you need to change it: both in `@remix-run/react/components.js` and `@remix-run/react/esm/components.js`.

---

Now, from what I can tell, the issue with the `search` part is that you can't just replace `useResolvedPath` with `useLocation`, because `useResolvedPath` parses the `action` prop the `Form` component has received, defaulting to `.` if no explicit `action` prop has been set. So, if you were to replace the `useResolvedPath().search` with `useLocation().search`, then you would overwrite any `search` part that could be explicitly set using the `action` prop.

The solution would look like this:
```diff
 export function useFormAction(
   action = ".",
   // TODO: Remove method param in v2 as it's no longer needed and is a breaking change
   method: FormMethod = "get"
 ): string {
   let { id } = useRemixRouteContext();
   let path = useResolvedPath(action);
   let search = path.search;
   let isIndexRoute = id.endsWith("/index");
+  let location = useLocation();
+
+  if (action === ".") {
+    search = location.search
+  }

   if (action === "." && isIndexRoute) {
     search = search ? search.replace(/^\?/, "?index&") : "?index";
   }

   return path.pathname + search;
 }
```

---

E.g. 
```
1️⃣
Location: /login?redirectTo=/profile
Form action: undefined

useResolvedPath
    --> 💔 <Form method="post" action="/login" />

useLocation
    --> 💚 <Form method="post" action="/login?redirectTo=/profile" />

useResolvedPath + useLocation
    --> 💚 <Form method="post" action="/login?redirectTo=/profile" />
```

```
2️⃣
Location: /login?redirectTo=/profile
Form action: /custom-path?foo=bar

useResolvedPath
    --> 💚 <Form method="post" action="/custom-path?foo=bar" />

useLocation
    --> 💔 <Form method="post" action="/custom-path?redirectTo=/profile" />

useResolvedPath + useLocation
    --> 💚 <Form method="post" action="/custom-path?foo=bar" />
```

**Comment by nivekithan** [comment]
@ionut-botizan  yeah you are correct, I cloned the remix repo locally and changed the code in `packages/remix-react/components.tsx` , the error is nowhere to be seen. 

On your code, if we explicit set the `action` to `./` or to `././` or to `./././` then also we will lose the `search` part, where as setting the `action`  to `.` will not lose the `search` part. 


if we assume the behaviour of `action` to be same as `to` in `<Link to={...} > </Link>`, then when we explicitly set `action` to `.`, we should lose `search` part. We only should consider `search` part when `action` is `undefined`

So code should look like this

```ts

/**
 * Resolves a `<form action>` path relative to the current route.
 *
 * @see https://remix.run/api/remix#useformaction
 */
export function useFormAction(
  action?: string,
  // TODO: Remove method param in v2 as it's no longer needed and is a breaking change
  method: FormMethod = "get"
): string {
  let { id } = useRemixRouteContext();
  let path = useResolvedPath(action ? action : ".");
  let search = path.search;
  let isIndexRoute = id.endsWith("/index");
  let location = useLocation();

  if (action === undefined) {
    search = location.search;
  }

  if ((action === undefined || action === ".") && isIndexRoute) {
    search = search ? search.replace(/^\?/, "?index&") : "?index";
  }

  return path.pathname + search;
}
```
And we also have to change `FormImpl` to this
```ts
let FormImpl = React.forwardRef<HTMLFormElement, FormImplProps>(
  (
    {
      reloadDocument = false,
      replace = false,
      method = "get",
      action,
      encType = "application/x-www-form-urlencoded",
      fetchKey,
      onSubmit,
      ...props
    },
    forwardedRef
  ) {...}
```

**Comment by jaschaio** [comment]
Is there any workaround? I tried the one from @kiliman but then I get a `405 Method now allowed` error

**Comment by kiliman** [comment]
If you're posting to an index route, then make sure you append `?index` to the URL.

**Comment by jaschaio** [comment]
@kiliman this still doesn't work when using a remix `Form` potentially because of #3564

**Comment by ScottAgirs** [comment]
> ?index



> 

This was good to me, haha.

Any chance Remix could make this more ergonomic? : ) 🤞🏼

**Comment by lili21** [comment]
the latest version(1.6.8) already fixed the issue.

**Comment by TheRealFlyingCoder** [comment]
I'm just closing this as stale, I'm pretty sure it was fixed but haven't had any confirmation from the team.

If it's not we can re-open

**Comment by uhrohraggy** [comment]
@TheRealFlyingCoder we're on 1.9.0 using a GET form submission, and the search/query params are still lost. Perhaps this is in conjunction with `useSubmit`.

```
import { Form, useSubmit } from "@remix-run/react";
...
const submit = useSubmit();
function handleChange(event) {
    submit(event.currentTarget, { replace: true });
  }

return (
    <Form
      method="get"
      onChange={handleChange}
       ...
)
```
package.json
```
"@remix-run/node": "^1.9.0",
    "@remix-run/react": "^1.9.0",
    "@remix-run/serve": "^1.9.0",
    "@remix-run/server-runtime": "^1.9.0",
 ```

**Comment by Abdulbariii** [comment]
It's 2024, and this issue still exists. There should be an option within the Form to control whether existing search queries are removed or not.
