### ISSUE TITLE
Server Side Top Level Await does not work

### ISSUE THREAD

**Issue by joshocalico** [remix-run/remix#4348]
### What version of Remix are you using?

Latest (1.7.1)

### Steps to Reproduce

Use this export in any loader or server file.
```js
// My awesome computed function
const myPromise = new Promise((resolve) => {
    resolve("Hello Async");
});

const myResult = await myPromise;

export { myResult };
```

Note: this doesn't apply to client side Javascript/Typescript as Remix rightfully respects the tsconfig / jsconfig.

### Expected Behavior

It will evaluate the promise inside the module while it is being imported.

### Actual Behavior

The app doesn't build.

```
> remix build

Building Remix app in production mode...

✘ [ERROR] Top-level await is not available in the configured target environment ("node14")

    app/webapp.config.server.ts:91:22:
      91 │ export const colors = await getColors();
         ╵                       ~~~~~


Build failed with 1 error:
app/webapp.config.server.ts:91:22: ERROR: Top-level await is not available in the configured target environment ("node14")
Error
    at Object.onBuildFailure (/Users/joshuasteele/fluidity/fluidity-app/web/app.fluidity.money/node_modules/@remix-run/dev/dist/cli/commands.js:183:13)
    at buildEverything (/Users/joshuasteele/fluidity/fluidity-app/web/app.fluidity.money/node_modules/@remix-run/dev/dist/compiler.js:282:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/Users/joshuasteele/fluidity/fluidity-app/web/app.fluidity.money/node_modules/@remix-run/dev/dist/compiler.js:102:3)
    at async Object.build (/Users/joshuasteele/fluidity/fluidity-app/web/app.fluidity.money/node_modules/@remix-run/dev/dist/cli/commands.js:178:3)
    at async Object.run (/Users/joshuasteele/fluidity/fluidity-app/web/app.fluidity.money/node_modules/@remix-run/dev/dist/cli/run.js:496:7)
ERROR: "build:remix" exited with 1.
```

**Comment by machour** [comment]
The error message seems quite self-explanatory: top level await are not available for node14.
Can you try with node16 or maybe node14.14 (see https://github.com/evanw/esbuild/issues/253#issuecomment-1042859888)?

**Comment by joshocalico** [comment]
Problem is largely here, remix build doesn't allow you to configure any other target.
For my other non-remix related server things it works fine - I'm using target node16 in my own esbuild builds.

I'll reference the two files responsible.
https://github.com/remix-run/remix/blob/42fb183ce268dbaf5103e62022ce84c04f2f8178/packages/remix-dev/build.ts#L15-L20
https://github.com/remix-run/remix/blob/b35e1355d27353c1946c56842be992bbc5d1d60c/packages/remix-dev/compiler.ts#L75
https://github.com/remix-run/remix/blob/b35e1355d27353c1946c56842be992bbc5d1d60c/packages/remix-dev/compiler.ts#L105

I've thrown together a fork which bumps every reference to >= Node 14 to >= Node 14.8 and it seems to be working. The large problem is the actual ESBuild target used by remix isn't configurable.

**Comment by joshocalico** [comment]
I'll admit this is a bit of a bandaid solution as it just bumps the Node requirement and the ESBuild target. Would it make more sense to expose the ESBuild options to the remix configuration file? We're going to keep having these problems otherwise as javascript syntax changes.

**Comment by machour** [comment]
I'm failing to see the issue here @joshocalico: If you want to be able to use TLA in your project, then you need to make sure you run it on a compatible node version. What am I missing?

Opening the esbuild configuration to user land is a different topic, I think there's an open discussion about it.

**Comment by jgentes** [comment]
Would be great to have more modern Node support from Remix. Any update @machour?

**Comment by machour** [comment]
@jgentes someone from the Remix team will eventually pick this up, I'm just volunteering for triage.

**Comment by jgentes** [comment]
I *think* this may have been addressed by https://github.com/remix-run/remix/pull/4034?

**Comment by machour** [comment]
@mcansh is that the case?

**Comment by mcansh** [comment]
not that i know of, esbuild's target is still `node14`, so while typescript will be okay with it, esbuild will still throw 
![image](https://user-images.githubusercontent.com/11698668/202863539-02726e17-047c-4276-8083-81f870fef3b2.jpeg)

**Comment by machour** [comment]
Converting this to a Proposal discussion, as per our [Development Process](https://remix.run/docs/en/v1/pages/contributing#development-process).
