### ISSUE TITLE
V2 routing doesn't detect new routes

### ISSUE THREAD

**Issue by xHomu** [remix-run/remix#5247]
### What version of Remix are you using?

v1.11.1

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. `npx create-remix` and go through all the steps.
2. add `future: {v2_routeConvention: true,}` to`remix.config.js`.
3. `npm run dev` 
4. Create `app/routes/test.tsx` and a basic export default component.
5. Visit `localhost:3000/test`

### Expected Behavior

See the test route.

### Actual Behavior

404 Not Found thrown.

* If we restart the dev server manually, route renders correctly.
* Untoggle v2_routeConvention, route renders correctly.
* Edits to existing route files work as expected.

sample repo:
https://github.com/xHomu/remix-v2-routes-new2/blob/main/app/routes/test.tsx

**Comment by mcansh** [comment]
unfortunately i'm unable to reproduce

both the CLI and browser pick up the new file

```log
Done in 24ms.
💿 File created: app/routes/my-new-route.tsx
💿 Rebuilding...
💿 Rebuilt in 97ms
GET / 200 - - 3.490 ms

Rebuilding...

Done in 33ms.
💿 File changed: app/routes/my-new-route.tsx
💿 Rebuilding...
💿 Rebuilt in 83ms
GET / 200 - - 5.460 ms
GET /my-new-route 200 - - 17.775 ms
```

**Comment by xHomu** [comment]
Mmm, still getting this error. I'll switch up my setup a bit to see if I can narrow down if it's a local issue:
![image](https://user-images.githubusercontent.com/84349818/214685596-dac9ac1a-7338-4c61-a3c9-304bcb37d950.png)

**Comment by xHomu** [comment]
Tested on different environments, seems to be a Windows-specific bug:

✔️ StackBlitz
✔️ Mac
❌ Windows laptop
❌ Windows PC

**Comment by mcansh** [comment]
hm, i'll pull windows up shortly and see what i can come up with

**Comment by mcansh** [comment]
yep, fast glob will return posix style paths `/` instead of windows `\\` - will go out in the next release

**Comment by trevor-hackett** [comment]
I'm still seeing this issue on Windows. Has the fix been released?

**Comment by stepniaczky** [comment]
> I'm still seeing this issue on Windows. Has the fix been released?

I have the same

**Comment by stepniaczky** [comment]
> I'm still seeing this issue on Windows. Has the fix been released?

I'm seeing it as well

**Comment by mcansh** [comment]
it seems to be hit or miss on when it reloads for some reason as creating 2 files does trigger it for me - looking into it

this time it is not a path separator issue though 😉

**Comment by stepniaczky** [comment]
@mcansh, Unfortunately, nothing has changed

**Comment by trevor-hackett** [comment]
> @mcansh, Unfortunately, nothing has changed

Same. Still not working. For me, it never works until the process is restarted

**Comment by stepniaczky** [comment]
In my case, however, the error was on my side because I was using routes nested in directories and subdirectories according to the official Get Started Remix (https://remix.run/docs/en/1.15.0/tutorials/blog), the documentation (https://remix.run/docs/en/1.15.0/guides/routing) and other sources on the internet that I came across. Only later did I realise that the routes directory must look like this is described here: https://remix.run/docs/en/main/file-conventions/route-files-v2

**Comment by qicrosoft** [comment]
Why hasn't it been updated? That such an obvious problem has not been solved for so long? Looks like a toy, too afraid to use it for a formal project.

**Comment by bamontales** [comment]
Same with me using v1.15.0 and Windows, still can't detect new routes.

**Comment by machour** [comment]
From what I understand, this should be fixed in 1.16.0
Can someone confirm? 🙏🏼

**Comment by xHomu** [comment]
> From what I understand, this should be fixed in 1.16.0 Can someone confirm? 🙏🏼

@machour seems like still unresolved:

![image](https://user-images.githubusercontent.com/84349818/235546820-1edcf642-47f4-4f91-a25b-bdd0cbfaa7e1.png)

this is despite remix routes picking up the file:

![image](https://user-images.githubusercontent.com/84349818/235546891-6d337cff-fb51-4454-8e35-b94be8557454.png)

**Comment by trevor-hackett** [comment]
Can confirm that the same behavior is still happening.

When the dev server is running, all route changes (new files, deletions, renames, etc.) are not detected until the dev server is stopped and restarted.

**Comment by mcansh** [comment]
> this time it is not a path separator issue though 😉

turns out it is a path issue, but higher up the chain..

**Comment by bluefire2121** [comment]
I'm having this issue on Windows. Was working in 1.14.3, no longer working. Currently using 1.16.0.

**Comment by trevor-hackett** [comment]
Just noticed that this is now working in the latest nightly builds!

**Comment by mcansh** [comment]
> Just noticed that this is now working in the latest nightly builds!

woo!

i messed up the bot so it didn't post an update here with details, sorry!

the version is `0.0.0-nightly-6563a94-20230504` for future folks
