### ISSUE TITLE
Build on Vercel fails with v2_routeConvention 

### ISSUE THREAD

**Issue by sohai** [remix-run/remix#5488]
### What version of Remix are you using?

1.13.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```
npx create-remix@latest
```
_What type of app do you want to create?_
Just the basics
_Where do you want to deploy? Choose Remix App Server if you're unsure; it's easy to change deployment targets._
Vercel

add v2_routeConvention to remix.config.js

```javascript
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  ignoredRouteFiles: ["**/.*"],
  // When running locally in development mode, we use the built-in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === "development" ? undefined : "./server.js",
  serverBuildPath: "api/index.js",
  future: {
    v2_routeConvention: true,
  },
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
};

```

change `routes/index.ts` to `routes/_index.ts`

Create a new Vercel project and connect with the repo. 

Example repo: https://github.com/sohai/remix-vercel

### Expected Behavior

The project is successfully built.

### Actual Behavior

Build step fails with  the following error 
```
Error: File not found: /vercel/path0/app/outes/_index.tsx
```

Note `outes` instead of `routes`

**Comment by airjp73** [comment]
I think this might be on Vercel rather than Remix. Running `vercel build` locally, I couldn't reproduce this. I upgraded the vercel cli with `npm i -g vercel@latest`, and now I get the exact same error when I do `vercel build`. I wonder if vercel has somehow included 1.12.0 (which had this issue) in their CLI.

**Comment by machour** [comment]
Will be fixed by https://github.com/vercel/vercel/pull/9455

**Comment by airjp73** [comment]
In the meantime, you can workaround the issue by setting the `VERCEL_CLI_VERSION` env variable in your project settings to `vercel@28.15.3`

**Comment by DennisSimon** [comment]
Hey @machour, @airjp73, i work with @sohai on this. 
Thanks for your pointers on this issue. I could confirm that the workaround that @airjp73 suggested works for deployments.
Thanks a ton!

**Comment by marcojakob** [comment]
@machour 

> Will be fixed by [vercel/vercel#9455](https://github.com/vercel/vercel/pull/9455)

It was just merged but that didn't really fix it for me. Still getting:

```
Error: File not found: /vercel/path0/app/outes/_index.tsx
```

**Comment by airjp73** [comment]
Yeah, looking at that PR, that won't actually fix it. The issue is in the vercel CLI itself.

**Comment by v-zdorovcev** [comment]
> vercel@28.15.3

For me, this causes a new error  

```
[GET] /
20:02:17:08
2023-02-19T13:02:17.733Z	undefined	ERROR	TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at groupRoutesByParentId (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:19:10)
    at Object.createRoutes (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:31:67)
    at Object.createRequestHandler (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:27:25)
    at createRequestHandler (/var/task/node_modules/@remix-run/vercel/dist/server.js:34:28)
    at Object.<anonymous> (/var/task/api/__vc_handler.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
RequestId: 243f5a1e-88b5-43ab-a30c-aa82eb33c2f1 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by TooTallNate** [comment]
This is fixed now as of Vercel CLI v28.16.6 ([PR](https://github.com/vercel/vercel/pull/9519)).

**Comment by agcty** [comment]
@TooTallNate @DennisSimon @sohai I still can't deploy a remix app with v2_routeConvention turned on even with v28.16.6. The issue seems to be pathless layout routes. 

Here's my reproduction repo: https://github.com/agcty/test-deploy-root

When you have a file structure like this:

<img width="343" alt="image" src="https://user-images.githubusercontent.com/12101091/221611402-212b761f-65c4-4e5f-80e1-5dd3c1cc9c32.png">

The vercel output looks like this:

<img width="364" alt="image" src="https://user-images.githubusercontent.com/12101091/221611572-a6b47891-d9e5-4f60-9cbf-e595e22a3a35.png">

and `vercel build` throws `Error: ENOENT: no such file or directory, readlink '/vercel/output/functions/.func'`

**Comment by fweth** [comment]
I have a problem with my `$slug.($lang).jsx` route as well.  Including `future: { v2_routeConvention: true }` just broke my deploy altogether.

BTW, what's the correct config for Vercel?  `serverBuildPath: "api/index.js"` is not needed anymore, so is it basically just like [this](https://github.com/vercel/vercel/blob/main/examples/remix/remix.config.js)?  (Because it differs from the [Remix template](https://github.com/remix-run/remix/tree/a2ce6f77b6cc1e0b245fcadbd1027ddaac1da240/templates/vercel)...

**Comment by frontsideair** [comment]
I'm getting the new error from https://github.com/remix-run/remix/issues/5488#issuecomment-1435984104 with `vercel@28.16.15` as of yesterday. (Probably before that, as runtime errors were gobbled up before.) I have explicitly disabled v2 route convention in the config by the way.

**Comment by vimtor** [comment]
Same issue here

**Comment by p-christ** [comment]
Same here, it builds fine on vercel but then when i go to the website i get this error in the vercel logs - any idea how to fix this?

`TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at groupRoutesByParentId (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:19:10)
    at Object.createRoutes (/var/task/node_modules/@remix-run/server-runtime/dist/routes.js:31:67)
    at createRequestHandler (/var/task/node_modules/@remix-run/server-runtime/dist/server.js:27:25)
    at file:///var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs:14:23
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
RequestId: e6be20c2-59f4-43f3-9db3-55edb04fc019 Error: Runtime exited without providing a reason
Runtime.ExitError`
