### ISSUE TITLE
Support TS 5 extends array

### ISSUE THREAD

**Issue by jasonkuhrt** [remix-run/remix#5931]
### What version of Remix are you using?

1.14.3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

1. Have project use [TS 5 feature of extends array](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#supporting-multiple-configuration-files-in-extends).
2. Try `remix build`. See error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array
    at new NodeError (node:internal/errors:387:5)
    at validateString (node:internal/validators:162:11)
    at Object.join (node:path:1172:7)
    at Object.loadTsconfig (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/tsconfig-paths@4.1.2/node_modules/tsconfig-paths/lib/tsconfig-loader.js:106:39)
    at Object.writeConfigDefaults (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/@remix-run+dev@1.14.3/node_modules/@remix-run/dev/dist/compiler/utils/tsconfig/write-config-defaults.js:77:35)
    at Object.readConfig (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/@remix-run+dev@1.14.3/node_modules/@remix-run/dev/dist/config.js:205:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.build (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/@remix-run+dev@1.14.3/node_modules/@remix-run/dev/dist/cli/commands.js:186:18)
    at async Object.run (/Users/jasonkuhrt/projects/prisma/pdp-spike-control-plane-v2/node_modules/.pnpm/@remix-run+dev@1.14.3/node_modules/@remix-run/dev/dist/cli/run.js:456:7) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Expected Behavior

Remix supports any valid TS config.

### Actual Behavior

Remix does not support any valid TS config.

**Comment by kiliman** [comment]
Remix uses `esbuild` as the underlying compiler. Remix v1.14.3 is currently pinned to esbuild v0.16.3.

It doesn't look like esbuild started supporting TS 5 until v0.17.5, although I'm unsure if it supports the *extends array* feature.

It's difficult to say when Remix will update to the latest esbuild version.

**Comment by MichaelDeBoey** [comment]
`esbuild` will be updated to 17.6 in the next release (see #5922 & #5925)

**Comment by machour** [comment]
This should now be fixed (1.16.0).

**Comment by atoi** [comment]
Still does not work for me (Remix 1.17.1).
It seems multiple inheritance in `tsconfig.json` landed to rebuild only since `0.18.0`

https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0180
