### ISSUE TITLE
"unstable_dev" doesn't kill app server on exit (Windows)

### ISSUE THREAD

**Issue by trevor-hackett** [remix-run/remix#6322]
### What version of Remix are you using?

1.16.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

On a Windows machine, create a new Remix app with unstable_dev enabled. (ex: `npx create-remix@latest --template https://github.com/remix-run/remix/tree/templates_v2_dev/templates/remix my-app`)

Run the app. (`npm run dev`)

Kill the process (ex: `CTRL-C`)

### Expected Behavior

Dev server and app server should exit

### Actual Behavior

Dev server exits but app server process continues to run and has to be killed separately.

**Comment by pcattori** [comment]
should be fixed by #6289

**Comment by trevor-hackett** [comment]
This isn't about the development loop (restart app server on changes). 

This is when you kill the development process altogether. The child process (app server) is not killed with the dev app. The app server process is left running and you can't start up a new process (`npm run dev`) until you manually kill the node process

**Comment by trevor-hackett** [comment]
Just to confirm. I installed the latest nightly and it is still happening.

For more context this is what I'm doing:

```
> dev
> remix dev

💿 Building...
💿 Built in 537ms
Waiting for app server (07d97bd0)
> remix-serve build\index.js
Remix dev server ready
Remix App Server started at http://localhost:3000 (http://192.168.169.228:3000)
App server took 278ms
Terminate batch job (Y/N)? y
PS D:\dev\my-app22> npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 528ms
Waiting for app server (07d97bd0)
> remix-serve build\index.js
Remix dev server ready
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1740:16)
    at listenInCluster (node:net:1788:12)
    at Server.listen (node:net:1876:7)
    at Function.listen (D:\dev\my-app22\node_modules\.pnpm\express@4.18.2\node_modules\express\lib\application.js:635:24)
    at Object.<anonymous> (D:\dev\my-app22\node_modules\.pnpm\@remix-run+serve@1.16.0\node_modules\@remix-run\serve\dist\cli.js:48:84)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
```

Adding `windowsHide: false` to this fixes the issue:

https://github.com/remix-run/remix/blob/d8bcdc1b209d64cba4769ede49043f59ea22b0dc/packages/remix-dev/devServer_unstable/index.ts#L69-L77

Example:

```ts
 let newAppServer = execa.command(command, { 
   stdio: "pipe", 
   env: { 
     NODE_ENV: "development", 
     PATH: 
       bin + (process.platform === "win32" ? ";" : ":") + process.env.PATH, 
     REMIX_DEV_HTTP_ORIGIN: stringifyOrigin(httpOrigin), 
   }, 
   windowsHide: false
 }); 
```

```
PS D:\dev\my-app22> npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 528ms
Waiting for app server (07d97bd0)
> remix-serve build\index.js
Remix dev server ready
Remix App Server started at http://localhost:3000 (http://192.168.169.228:3000)
App server took 272ms
Terminate batch job (Y/N)? 
^C
PS D:\dev\my-app22> npm run dev

> dev
> remix dev

💿 Building...
💿 Built in 531ms
Waiting for app server (07d97bd0)
> remix-serve build\index.js
Remix dev server ready
Remix App Server started at http://localhost:3000 (http://192.168.169.228:3000)
App server took 268ms
```

**Comment by pcattori** [comment]
Thanks for the great detective work @trevor-hackett ! Adding this to the dev server TODOs

**Comment by pcattori** [comment]
@trevor-hackett merged #6322, so you'll be able to try this fix out on `nightly` tomorrow.

I'm working on getting Parallels setup for local Windows dev on my mac, but haven't done so yet. So in the meantime, any feedback from you or others using Windows is invaluable!
