### ISSUE TITLE
Dev Server crashes if saving before the last rebuild complete

### ISSUE THREAD

**Issue by xHomu** [remix-run/remix#6919]
### What version of Remix are you using?

v1.19.0

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

This is somewhat inconsistent, since it depends in part how quickly your server rebuilds.

This most frequently occurs when working on our production apps with longer rebuild time (https://github.com/manawiki/starrail) and CTRL+S save rapidly before rebuilds are ready.

The error usually looks like this:

```terminal
 info  rebuilding... (~ app/routes/_index.tsx)
 info  rebuilt (167ms)
 info  app server ready (9ms)
 info  hmr

 info  rebuilding... (~ app/routes/_index.tsx)
 info  rebuilt (291ms)
 info  rebuilding... (~ app/routes/_index.tsx)
 info  app server ready (37ms)
 info  hmr


/node_modules/@remix-run/server-runtime/dist/dev.js:26
      buildHash: build.assets.version
                              ^
TypeError: Cannot read properties of undefined (reading 'version')
    at broadcastDevReady (/node_modules/@remix-run/server-runtime/dist/dev.js:26:31)
    at FSWatcher.<anonymous> (file:///server.js:64:5)
 info  rebuilt (511ms)
```

I'll try to see if I can create a reproducible step with a simpler template.

### Expected Behavior

Dev Server crashes gracefully.

### Actual Behavior

Dev Server crash and force a manual restart.

**Comment by xHomu** [comment]
![image](https://github.com/remix-run/remix/assets/84349818/d8f3abe9-cc4d-4dea-8cbb-9d0c75e1e877)

**Comment by pcattori** [comment]
@xHomu could you patch  `if (build.assets === undefined) return;` as the first line of `broadcastDevReady` in `node_modules/@remix-run/server-runtime/dist/dev.js`? I'm curious if just ignoring empty `build`s will fix the issue and not cause any rebuilds to be missed by the dev server.

**Comment by ngbrown** [comment]
@xHomu This looks like it might be the same/similar as something I reported in #6831. I had a large server bundle size and would occasionally have file reading issues because the server was triggered by chokidar to re-read the bundle before the writing finished.

Does removing the `createDevRequestHandler()` path and removing `--manual` fix it (with the cost of the server restarting on every change). Or does adding the `awaitWriteFinish` option to `chokidar.watch()` fix it? That worked in my case.

**Comment by xHomu** [comment]
@ngbrown restart on every change would be a big hit on the DX, so I'm gonna give the awaitWriteFinish option a try and see if it helps. Just `.watch(BUILD_PATH, { ignoreInitial: true, awaitWriteFinish: true })` or do you have a specific setting for it that worked for you?

**Comment by ngbrown** [comment]
@xHomu The default timeout for `awaitWriteFinish` is 2 seconds, so I lowered the `stabilityThreshold` to 200 ms, and that was working for me. See the diff in https://github.com/remix-run/remix/issues/6831#issuecomment-1636273169.

**Comment by xHomu** [comment]
@ngbrown no crushes in an afternoon after the change, a good sign!

```jsx
   chokidar
      .watch(BUILD_PATH, {
         ignoreInitial: true,
         awaitWriteFinish: { stabilityThreshold: 200 },
      })
      ```

**Comment by xHomu** [comment]
I made a PR #6922 to the Express template to include `awaitWriteFinish`. Is this enough to resolve #6831 and #6919, at least for Remix dev v2 server on Express?

**Comment by ngbrown** [comment]
@pcattori I thought of another way to handle this than using `awaitWriteFinish` on `chokidar`... Since `chokidar` in the server is only watching a single file, if the build saved to a temporary file, and then when saving was done, rename/move the file to the target file name, replacing the old one, it would be an almost atomic action, and reloading should take place without a hitch.

**Comment by xHomu** [comment]
Sure let me give that a shot today. Should I go ahead and close this pr until we settle on best practices?

**Comment by pcattori** [comment]
> Sure let me give that a shot today. Should I go ahead and close pr #6922 until we settle on best practices?

Just made it into a Draft PR for now

**Comment by xHomu** [comment]
@pcattori I pushed the watch_path change to the mana production code and seems to be working well, will report back if we saw any instability https://github.com/manawiki/core/commit/2b81f4d2f8744d1bb14ac2fbf784c9719f11f22b#comments

so far so good

**Comment by xHomu** [comment]
Mhm, experiencing some weird hmr not refreshing issues with one of the remix-v2-dev branches with `metafile.server.json`, looking into it. https://github.com/xHomu/remix-v2-server/tree/esm-server.js

**Comment by ngbrown** [comment]
Watching `"./build/metafile.server.json"` (and removing `awaitWriteFinish`) isn't working for me. The server reloads, but on a manual refresh of the browser, the server is now trying to serve up the old missing chunks to the browser.

The HMR also seemed to stop working as the new chunks aren't loading. I'm on Remix 1.19.2 and #6772 should have landed in 1.19.0?

**Comment by xHomu** [comment]
@ngbrown It's really strange, it works just fine on some of my repos, and not others. Have you tried adding awaitWriteFinish back in and see if it do anything on your end? 

✔️  mana.wiki (cjs/server.ts) https://github.com/manawiki/core
✔️ repay (cjs/server.ts) https://github.com/manawiki/repay

remix-v2-server:

* ✔️ esm/server.ts https://github.com/xHomu/remix-v2-server/tree/esm-server.ts
* ❌ esm/server.js https://github.com/xHomu/remix-v2-server/tree/esm-server.js
* ❌ cjs/server.ts https://github.com/xHomu/remix-v2-server/tree/cjs-server.ts
* ❌cjs/server.js https://github.com/xHomu/remix-v2-server/tree/cjs-server.js

My presumption that was this was particular to specific typescript/ esm combination turns out to be wrong, or else there's no reason why mana and repay works but the cjs/server.ts branch of remix-v2-server didn't.

**Comment by ngbrown** [comment]
@xHomu Adding back in `awaitWriteFinish` and still watching `metafile.server.json` wouldn't prove anything because it would then be relying on the timing of `200` ms (or whatever the configuration is set to). for the `index.js` to finish being written. It would be mostly a coincidence if it worked.

**Comment by pcattori** [comment]
> My reading of this is that the metadata is written out before the bytes in the `outputFiles`:
> 
> https://github.com/remix-run/remix/blob/8779b24d0e51cc49a887d16afab9789557b80124/packages/remix-dev/compiler/server/compiler.ts#L143-L147

Oh yea, good point. I forgot that we are manually writing the server build file later and not depending on `esbuild` to write it for us.

**Comment by pcattori** [comment]
For now, let's rely on `awaitWriteFinish`. After v2 releases, I'll look into this some more.

**Comment by pcattori** [comment]
Ok version `2.0.0-pre.3` includes changes to write a `version.txt` file in the server build directory (not the public build directory) _after_ the server build has been completely written.

Technically, there's still a chance of a race condition, but should be much rarer plus I have additional plans to fix that. But for now you should be able to watch `version.txt` for changes instead of directly watching the server build:

```diff
chokidar
- .watch(buildPath, { ignoreInitial: true })
+ .watch(path.resolve("build/version.txt", { ignoreInitial: true })
  .on("add", handleServerUpdate)
  .on("change", handleServerUpdate);
```

@xHomu @ngbrown or anyone want to try it out?

**Comment by xHomu** [comment]
Something came up atm, but I'll be able to give it a whirl tonight.

**Comment by xHomu** [comment]
@pcattori happy to report back that all status looks green, and none of the repos I'm actively maintaining experience any of the previous downsides!

✔️  mana.wiki (cjs/server.ts) https://github.com/manawiki/core
✔️ repay (cjs/server.ts) https://github.com/manawiki/repay

remix-v2-server:

* ✔️ esm/server.ts https://github.com/xHomu/remix-v2-server/tree/esm-server.ts
* ✔️ esm/server.js https://github.com/xHomu/remix-v2-server/tree/esm-server.js
* ✔️ cjs/server.ts https://github.com/xHomu/remix-v2-server/tree/cjs-server.ts
* ✔️cjs/server.js https://github.com/xHomu/remix-v2-server/tree/cjs-server.js

Also seems a tad faster too? Might just be happy thoughts. 

[Sample PR](https://github.com/xHomu/remix-v2-server/commit/9f7dd748e7458944312c226e8c451f873cc59799)
----

**Comment by pcattori** [comment]
Fixed by #7469 and #7470

**Comment by chankruze** [comment]
It's still happening 

![image](https://github.com/remix-run/remix/assets/29806845/bc6b2949-a4bf-45b0-8ff8-1caa12b8162c)

```
"@remix-run/css-bundle": "^2.0.0",
"@remix-run/node": "^2.0.0",
"@remix-run/react": "^2.0.0",
"@remix-run/serve": "^2.0.0",
"@remix-run/dev": "^2.0.0",
```

**Comment by pcattori** [comment]
@chankruze the fixes were merged after v2. they are available on nightly (`npx upgrade-remix nightly`) if you want to try them out.
