### ISSUE TITLE
Vite: error in pnpm monorepo when using default entries

### ISSUE THREAD

**Issue by itsMapleLeaf** [remix-run/remix#7722]
### What version of Remix are you using?

0.0.0-experimental-5603af8a3

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

```bash
git clone -b default-entries https://github.com/itsMapleLeaf/remix-vite-workspaces.git
cd remix-vite-workspaces
pnpm install
cd workspaces/web
pnpm dev
```

### Expected Behavior

The app should run without errors

### Actual Behavior

You get an error in the browser that it can't find the default entry files outside of the root workspace:
```
Cannot resolve asset path "C:\dev\demo\remix-vite-workspaces\node_modules\.pnpm\@remix-run+dev@0.0.0-experimental-5603af8a3_@remix-run+serve@0.0.0-experimental-5603af8a3_typescript@5.2.2_vite@4.5.0\node_modules\@remix-run\dev\dist\config\defaults\entry.server.node.tsx" outside of root directory "C:\dev\demo\remix-vite-workspaces\workspaces\web".
    at resolveFileUrl (C:\dev\demo\remix-vite-workspaces\node_modules\.pnpm\@remix-run+dev@0.0.0-experimental-5603af8a3_@remix-run+serve@0.0.0-experimental-5603af8a3_typescript@5.2.2_vite@4.5.0\node_modules\@remix-run\dev\dist\vite\plugin.js:74:11)
    at getServerEntry (C:\dev\demo\remix-vite-workspaces\node_modules\.pnpm\@remix-run+dev@0.0.0-experimental-5603af8a3_@remix-run+serve@0.0.0-experimental-5603af8a3_typescript@5.2.2_vite@4.5.0\node_modules\@remix-run\dev\dist\vite\plugin.js:194:51)
    at async Context.load (C:\dev\demo\remix-vite-workspaces\node_modules\.pnpm\@remix-run+dev@0.0.0-experimental-5603af8a3_@remix-run+serve@0.0.0-experimental-5603af8a3_typescript@5.2.2_vite@4.5.0\node_modules\@remix-run\dev\dist\vite\plugin.js:411:20)
    at async Object.load (file:///C:/dev/demo/remix-vite-workspaces/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:44323:32)
    at async loadAndTransform (file:///C:/dev/demo/remix-vite-workspaces/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:54954:24)
```

Workaround: run `pnpm remix reveal` in the workspace to create default entries

**Comment by pcattori** [comment]
Yep, [this check](https://github.com/remix-run/remix/blob/dev/packages/remix-dev/vite/plugin.ts#L86-L92) is probably to aggressive. Looking into it

**Comment by markdalgleish** [comment]
This should be fixed by https://github.com/remix-run/remix/pull/7913.

**Comment by vanvix** [comment]
Hello, this issue is present on Windows, tested again today in nightly version and still doesn't work. Tested on MacOS and works just fine.

Here's link to the original comment: https://github.com/remix-run/remix/issues/7960#issuecomment-1808820142

Basicaly, solution for this is to run `npx remix reveal` in the workpace directory you can't run and 2 new `.entry` files will appear. I'm leaving the comment here suggested by @mrksbnch.

**Comment by alindsay55661** [comment]
I ran into a different error but the workarounds here resulted in a fix. In my case, the app simply wouldn't start properly:

<img width="688" alt="image" src="https://github.com/remix-run/remix/assets/270710/d524fadb-1aa3-44aa-af92-c5440b23d530">


Using `pnpm remix reveal` solved the issue. You can see I'm uinsg Windows as well.

**Comment by hi-ogawa** [comment]
Could someone test this patch on Windows? https://github.com/remix-run/remix/pull/8057
I'm hoping that this could fix this issue by changing from `/@fsC:\Users\...` to `/@fs/C:/Users/...`, but currently I cannot find a way to this change on CI nor locally since I don't have Windows PC.

**Comment by alindsay55661** [comment]
@hi-ogawa I can confirm that your patch solves my specific problem on Windows.

**Comment by pcattori** [comment]
Windows issues should be fixed by #8057 . You can try it out on `nightly` starting tomorrow
