### ISSUE TITLE
[Vite plugin]: assets only imported in resource routes not included in build output

### ISSUE THREAD

**Issue by manzano78** [remix-run/remix#7847]
### What version of Remix are you using?

v0.0.0-nightly-99a8d9c-20231031

### Are all your remix dependencies & dev-dependencies using the same version?

- [X] Yes

### Steps to Reproduce

Exactly the same issue than this one with the current compiler : https://github.com/remix-run/remix/issues/3414

1) Configure a project with the new unstable vite plugin as compiler
2) Create a resource route module which imports an asset as an URL and exposes it via the loader
 
```ts
import stylesheetUrl from './stylesheet.css?url'; // vite syntax

export function loader() {
  return json({ stylesheetUrl });
}
```
The issue also occurs on normal UI routes when the URL is only used in the loader, server side.

3) `npm run build`

### Expected Behavior

I would expect the asset to be included in the build output

### Actual Behavior

The asset is not included in the build output

**Comment by hi-ogawa** [comment]
It seems vite now provides `build.ssrEmitAssets` option which solved similar issues initially came up on sveltekit:
- https://github.com/vitejs/vite/discussions/13808

Further context on sveltekit:
- https://github.com/sveltejs/kit/issues/5240
  - this original issue also suggest potential user-side workaround in [this comment](https://github.com/sveltejs/kit/issues/5240#issuecomment-1398859362)
- https://github.com/sveltejs/kit/pull/9073

**Comment by manzano78** [comment]
@hi-ogawa, thanks for this information! I've just tried it, indeed it now generates the assets but in the server build folder instead of the public one. Consequently, it's still produces 404s in the browser :-/

**Comment by manzano78** [comment]
@hi-ogawa thank you very much for your help, I appreciate! This solution seems okay for the production build but I think it can't work in development mode with HMR and HDR, can it?

**Comment by hi-ogawa** [comment]
I attempted a fix in https://github.com/remix-run/remix/pull/7892, which mostly does the same thing as `cp ...` but does it inside vite plugin.

> This solution seems okay for the production build but I think it can't work in development mode with HMR and HDR, can it?

I don't think this specific issues are relevant for `dev` since vite serves asset files without renaming asset file with hash etc...

But, looking at your case, the usage of `./stylesheet.css?url` might have a different issue with vite https://github.com/remix-run/remix/issues/7786, so `ssrEmitAssets` will not probably solve that part of a problem.

**Comment by markdalgleish** [comment]
This is fixed by https://github.com/remix-run/remix/pull/7892.

Since you're using `.css?url` imports, you should also be running Vite v5.1.0-beta.0 or later (currently at v5.1.0-beta.6) and setting `build.cssMinify` to `true` in your Vite config. This setting will be enabled by default in the next release of the Remix Vite plugin.

**Comment by manzano78** [comment]
@markdalgleish, despite the latest version of Vite (v5.1.1), the latest Remix nightly (v0.0.0-nightly-4111fd1-20240210) and `build.cssMinify` to `true`, I can still reproduce this issue. The CSS files which are only referenced server side with `.css?url` are not copied to the client assets. Should I open a new issue?
