### ISSUE TITLE
Remix Vite has hydration mismatch when using the `useId` hook

### ISSUE THREAD

**Issue by ShafSpecs** [remix-run/remix#8509]
### Reproduction

Seems to be an exact replica of this Next issue: https://github.com/vercel/next.js/issues/53110

I am utilizing `@headlessui/react` in my application and I get multiple hydration error in Remix Vite when I utilise the `Menu` component. Digging further into the cause of the mismtach with [Remix Development Tools](https://github.com/Code-Forge-Net/Remix-Dev-Tools), the error is caused by mismatching menu ids. Digging further into the cause in headless ui repo, stumbled across this comment: https://github.com/tailwindlabs/headlessui/issues/2606#issuecomment-1647608684 which states that headless ui uses `useId` from `react` to generate the ids.

Trying to replicate it can be easily achieved with this code block:
```tsx
import {useId} from "react"

export function Example() {
  let id = useId()
  return <div data-id={id}>My Example</div>
}
```
RDT shows the following mismatch:
![image](https://github.com/remix-run/remix/assets/69679506/d6e09006-3bcd-4a2a-bf0c-e37ab26fd24b)

Not sure if this is Vite or a Remix thing. Haven't tried replicating in a new, pure Remix environment yet
Thank you.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 4800HS with Radeon Graphics
    Memory: 4.81 GB / 15.42 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.11.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (120.0.2210.133)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @remix-run/dev: ^2.4.1 => 2.4.1
    @remix-run/eslint-config: ^2.4.1 => 2.4.1
    @remix-run/node: ^2.4.1 => 2.4.1
    @remix-run/react: ^2.4.1 => 2.4.1
    @remix-run/serve: ^2.4.1 => 2.4.1
    vite: ^5.0.0 => 5.0.10
```

### Used Package Manager

npm

### Expected Behavior

No hydration mismatch as `id` should be constant on server and client

### Actual Behavior

Mismatch occurs

**Comment by brophdawg11** [comment]
Could you double check this against `2.5.0` and make sure you have the right RR version?  We found an issue where internal `useFetcher` state was affecting the hydrated `useId` values, but that was fixed in [`react-router-dom@6.21.2`](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6212).

`useId` in the simplest case works OK (https://stackblitz.com/edit/remix-run-remix-em4rsa?file=app%2Froutes%2F_index.tsx), so if you're still seeing this could you provide a minimal reproduction?

**Comment by ShafSpecs** [comment]
> Could you double check this against `2.5.0` and make sure you have the right RR version?  We found an issue where internal `useFetcher` state was affecting the hydrated `useId` values, but that was fixed in [`react-router-dom@6.21.2`](https://github.com/remix-run/react-router/blob/main/CHANGELOG.md#v6212).
> 
> `useId` in the simplest case works OK (https://stackblitz.com/edit/remix-run-remix-em4rsa?file=app%2Froutes%2F_index.tsx), so if you're still seeing this could you provide a minimal reproduction? 

Sorry for not responding, I managed to fix it by first downgrading the remix version, and when a patch version was released, updated to it (2.5.1)

**Comment by Miloshinjo** [comment]
I still have this issue, using remix 2.8.1. I'm not using `useFetcher`, just a regular form. Also have this issue with radix ui elements that use Ids for aria attributes. They say react 18 shouldn't have these issues, but I'm using React 18 and still having them.

**Comment by brophdawg11** [comment]
Could you provide a reproduction if the issue you're seeing?

**Comment by Ian-inein** [comment]
I have this issue using radix.

Using Remix Dev Tools, gaves me this log:

`<html>
<body>

Server-Side Render | Client-Side Render
-- | --
  |   | Expand 194 lines ... |   |   |  
195 |   | </div> | 195 |   | </div>
196 |   | <div class="flex items-center justify-center"> | 196 |   | <div class="flex items-center justify-center">
197 | - | <button type="button" id="radix-:R2ml5:" aria-haspopup="menu" aria-expanded="false" | 197 | + | <button type="button" id="radix-:r6:" aria-haspopup="menu" aria-expanded="false"
198 |   | data-state="closed" class="group" data-testid="ProfileMenuId"> | 198 |   | data-state="closed" class="group" data-testid="ProfileMenuId">
199 |   | <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24" | 199 |   | <svg stroke="currentColor" fill="none" stroke-width="2" viewBox="0 0 24 24"
  |   | Expand 14 lines ... |   |   |  
214 |   | <div class=" flex flex-col gap-2"> | 214 |   | <div class=" flex flex-col gap-2">
215 |   | <h2 class="font-semibold text-lg">Empresa</h2> | 215 |   | <h2 class="font-semibold text-lg">Empresa</h2>
216 | - | <button type="button" role="combobox" aria-controls="radix-:R9b55:" aria-expanded="false" | 216 | + | <button type="button" role="combobox" aria-controls="radix-:r8:" aria-expanded="false"
217 |   | aria-autocomplete="none" dir="ltr" data-state="closed" class="flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 [&amp;>span]:line-clamp-1 hover:!bg-Acentuacion hover:!text-Blanco undefined input"><span style="pointer-events:none;"></span> | 217 |   | aria-autocomplete="none" dir="ltr" data-state="closed" class="flex h-9 w-full items-center justify-between whitespace-nowrap rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-sm ring-offset-background placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50 [&amp;>span]:line-clamp-1 hover:!bg-Acentuacion hover:!text-Blanco undefined input"><span style="pointer-events:none;"></span>
218 |   | <svg width="15" height="15" | 218 |   | <svg width="15" height="15"
  |   | Expand 4 lines ... |   |   |  
223 |   | </svg> | 223 |   | </svg>
224 |   | </button> | 224 |   | </button>
225 | - | <select aria-hidden="true" tabindex="-1" style="position:absolute;border:0;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;word-wrap:normal;"></select> | 225 | + | <select aria-hidden="true" tabindex="-1" style="position:absolute;border:0px;width:1px;height:1px;padding:0px;margin:-1px;overflow:hidden;clip:rect(0px,0px,0px,0px);white-space:nowrap;overflow-wrap:normal;"></select>
226 |   | </div> | 226 |   | </div>
227 |   | <hr class="border-[1px] border-Blanco3"> | 227 |   | <hr class="border-[1px] border-Blanco3">
  |   | Expand 3 lines ... |   |   |  
231 |   | <div collapsible="true" class="absolute w-full h-full" data-orientation="vertical"> | 231 |   | <div collapsible="true" class="absolute w-full h-full" data-orientation="vertical">
232 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3"> | 232 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3">
233 | - | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:R4rb55:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:Rrb55:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>operaciones</button></h3> | 233 | + | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:ra:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:r9:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>operaciones</button></h3>
234 | - | <div data-state="closed" id="radix-:R4rb55:" hidden="" role="region" aria-labelledby="radix-:Rrb55:" | 234 | + | <div data-state="closed" id="radix-:ra:" hidden="" role="region" aria-labelledby="radix-:r9:"
235 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" | 235 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
236 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div> | 236 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div>
237 |   | </div> | 237 |   | </div>
238 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3"> | 238 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3">
239 | - | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:R5bb55:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:R1bb55:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>finanzas</button></h3> | 239 | + | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:rc:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:rb:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>finanzas</button></h3>
240 | - | <div data-state="closed" id="radix-:R5bb55:" hidden="" role="region" aria-labelledby="radix-:R1bb55:" | 240 | + | <div data-state="closed" id="radix-:rc:" hidden="" role="region" aria-labelledby="radix-:rb:"
241 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" | 241 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
242 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div> | 242 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div>
243 |   | </div> | 243 |   | </div>
244 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3"> | 244 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3">
245 | - | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:R5rb55:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:R1rb55:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>contratos</button></h3> | 245 | + | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:re:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:rd:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>contratos</button></h3>
246 | - | <div data-state="closed" id="radix-:R5rb55:" hidden="" role="region" aria-labelledby="radix-:R1rb55:" | 246 | + | <div data-state="closed" id="radix-:re:" hidden="" role="region" aria-labelledby="radix-:rd:"
247 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" | 247 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
248 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div> | 248 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div>
249 |   | </div> | 249 |   | </div>
250 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3"> | 250 |   | <div data-state="closed" data-orientation="vertical" class="border-b border-Blanco3">
251 | - | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:R6bb55:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:R2bb55:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>CRM</button></h3> | 251 | + | <h3 data-orientation="vertical" data-state="closed" class="flex"><button type="button" aria-controls="radix-:rg:" aria-expanded="false" data-state="closed" data-orientation="vertical" id="radix-:rf:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>CRM</button></h3>
252 | - | <div data-state="closed" id="radix-:R6bb55:" hidden="" role="region" aria-labelledby="radix-:R2bb55:" | 252 | + | <div data-state="closed" id="radix-:rg:" hidden="" role="region" aria-labelledby="radix-:rf:"
253 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" | 253 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
254 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div> | 254 |   | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"></div>
255 |   | </div> | 255 |   | </div>
256 |   | <div data-state="open" data-orientation="vertical" class="border-b border-Blanco3"> | 256 |   | <div data-state="open" data-orientation="vertical" class="border-b border-Blanco3">
257 | - | <h3 data-orientation="vertical" data-state="open" class="flex"><button type="button" aria-controls="radix-:R6rb55:" aria-expanded="true" data-state="open" data-orientation="vertical" id="radix-:R2rb55:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>capital_humano</button></h3> | 257 | + | <h3 data-orientation="vertical" data-state="open" class="flex"><button type="button" aria-controls="radix-:ri:" aria-expanded="true" data-state="open" data-orientation="vertical" id="radix-:rh:" class="flex flex-1 gap-2 items-center justify-start py-4 text-sm font-medium transition-all hover:underline [&amp;[data-state=open]>svg]:rotate-180" data-radix-collection-item=""><svg width="15" height="15" viewBox="0 0 15 15" fill="none" xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 shrink-0 text-muted-foreground transition-transform duration-200"><path d="M3.13523 6.15803C3.3241 5.95657 3.64052 5.94637 3.84197 6.13523L7.5 9.56464L11.158 6.13523C11.3595 5.94637 11.6759 5.95657 11.8648 6.15803C12.0536 6.35949 12.0434 6.67591 11.842 6.86477L7.84197 10.6148C7.64964 10.7951 7.35036 10.7951 7.15803 10.6148L3.15803 6.86477C2.95657 6.67591 2.94637 6.35949 3.13523 6.15803Z" fill="currentColor" fill-rule="evenodd" clip-rule="evenodd"></path></svg>capital_humano</button></h3>
258 | - | <div data-state="open" id="radix-:R6rb55:" role="region" aria-labelledby="radix-:R2rb55:" | 258 | + | <div data-state="open" id="radix-:ri:" role="region" aria-labelledby="radix-:rh:"
259 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down" | 259 |   | data-orientation="vertical" class="pl-5 overflow-hidden text-sm data-[state=closed]:animate-accordion-up data-[state=open]:animate-accordion-down"
260 | - | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);"> | 260 | + | style="--radix-accordion-content-height:var(--radix-collapsible-content-height);--radix-accordion-content-width:var(--radix-collapsible-content-width);transition-duration:0s;animation-name:none;">
261 |   | <div class="pb-4 pt-0 flex flex-col gap-2"><a aria-current="page" class="bg-Acentuacion text-Blanco hover:bg-Acentuacion hover:text-Blanco rounded-md px-2 py-1 transition-colors ease-in-out duration-75" | 261 |   | <div class="pb-4 pt-0 flex flex-col gap-2"><a aria-current="page" class="bg-Acentuacion text-Blanco hover:bg-Acentuacion hover:text-Blanco rounded-md px-2 py-1 transition-colors ease-in-out duration-75"
262 |   | href="/platform/empresa-bcd98fca-b14d-4642-bfdd-a4e87c23b737/capital_humano/colaboradores">Colaboradores</a> | 262 |   | href="/platform/empresa-bcd98fca-b14d-4642-bfdd-a4e87c23b737/capital_humano/colaboradores">Colaboradores</a>
  |   | Expand 52 lines ... |   |   |  
315 |   | <footer class="fixed right-[1.5px] bottom-[1.5px] text-sm">powered by <span class="font-bold">Dittoh</span> | 315 |   | <footer class="fixed right-[1.5px] bottom-[1.5px] text-sm">powered by <span class="font-bold">Dittoh</span>
316 |   | </footer> | 316 |   | </footer>
317 | - | <div data-v-10465fb6=""> |   |   |  
318 | - |  |   |   |  
319 | - | </div> |   |   |  
320 |   | </body> | 317 |   | </body>


</body>
</html>`

**Comment by renevds** [comment]
@Miloshinjo did you ever manage to fix this on remix `2.8.1`? We are having the same problem with radix UI components but currently we don't have the option to quickly upgrade to a newer Remix.

**Comment by Miloshinjo** [comment]
@renevds sorry, it was a long time ago, but I totally moved my app to React Router 7 and I stopped having these issues... 

Sorry I was a long time ago and my memory escapes me, but I still have the `useId` call and no longer have these problems... I remember thinking of moving away from `useId` and using something more stable at the time... 

I can also add that moving to React Router 7 was not as painful as I expected it to be :)

**Comment by renevds** [comment]
@Miloshinjo thank you for the quick response! I am out of any inspiration so it seems we will be stuck with this until we migrate to React Router 7.

**Comment by muchisx** [comment]
@renevds did you find a solution? i'm experiencing the same in `2.16.2`

**Comment by renevds** [comment]
@muchisx still haven't found a fix, major problem for us as we can't move to react router, any fix on your side?

**Comment by muchisx** [comment]
hi @renevds 

no fix from my end other than manually adding the ids to components everywhere

but still some libraries automatically have inner components under the hood of which i cant control the if (dnd-kit for example) in that case i still havent found a fix
