### ISSUE TITLE
double slash followed by any char after domain causes infinite page reloading

### ISSUE THREAD

**Issue by dimanche-matin** [remix-run/remix#9692]
### Reproduction

Add double slash followed by any char after domain (e.g. [https://example.com//foo]()), then Enter.

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (8) arm64 Apple M1
    Memory: 59.33 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.7.1 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.5.0 - /opt/homebrew/bin/npm
  Browsers:
    Brave Browser: 125.1.66.115
    Chrome: 126.0.6478.127
    Edge: 126.0.2592.81
    Safari: 17.5
  npmPackages:
    @remix-run/dev: ^2.9.2 => 2.9.2 
    @remix-run/node: ^2.9.2 => 2.9.2 
    @remix-run/react: ^2.9.2 => 2.9.2 
    @remix-run/serve: ^2.9.2 => 2.9.2 
    vite: ^5.1.0 => 5.2.13
```

### Used Package Manager

npm

### Expected Behavior

404 Not Found

### Actual Behavior

Infinite reloading with this console error log:
"Initial URL (/) does not match URL at time of hydration (//foo), reloading page..."

Some web sites listed on https://remix.run/showcase are affected.

**Comment by brophdawg11** [comment]
This should be resolved via #9695 and available in the next release 👍

**Comment by dimanche-matin** [comment]
Bug persists on `2.11.0-pre.0`.

When navigating on `//foo` path :

On `2.9.2` :

On client :
<img width="485" alt="remix_2 9 2_p1_client_crop-min" src="https://github.com/user-attachments/assets/27a7cdcf-8a8a-4574-89d1-70df77ccb2ec">

On server :
Empty

On `2.11.0-pre.0` :

On client :
<img width="487" alt="remix_2 11 0-pre 0_p1_client_crop-min" src="https://github.com/user-attachments/assets/a7a72438-7ece-4b0d-8895-147563919291">

On server :
Empty

When navigating on `/foo//bar` path :

On `2.9.2` :

404 Not Found

On `2.11.0-pre.0` :

On client :
<img width="489" alt="remix_2 11 0-pre 0_p2-3_client_crop-min" src="https://github.com/user-attachments/assets/8165e4de-560b-4ccf-aab0-21198bf56fe6">

On server :
<img width="767" alt="remix_2 11 0-pre 0_p2_server_crop-min" src="https://github.com/user-attachments/assets/dbbe946c-d1d9-4337-9ecb-e1000a0a3264">

When navigating on `//foo//bar` path :

On `2.9.2` :

On client :
<img width="481" alt="remix_2 9 2_p3_client_crop-min" src="https://github.com/user-attachments/assets/28a5843c-ed9f-4d93-ac91-4bbd3340756e">

On server :
<img width="766" alt="remix_2 9 2_p3_server_crop-min" src="https://github.com/user-attachments/assets/bbbad831-e9ad-46e5-b00f-d630e89cf866">

On `2.11.0-pre.0` :

On client :
<img width="489" alt="remix_2 11 0-pre 0_p2-3_client_crop-min" src="https://github.com/user-attachments/assets/8165e4de-560b-4ccf-aab0-21198bf56fe6">

On server :
<img width="766" alt="remix_2 11 0-pre 0_p3_server_crop-min" src="https://github.com/user-attachments/assets/72cf77b6-2e56-4467-98ff-3dc0c23990a2">
